---
javascripts:
- base:
  - jquery.min
  - jquery.ui.core
  - jquery.ui.widget
  - jquery.ui.position
  - plugins/jquery.mousewheel
  - plugins/jquery.jscrollpane
  - plugins/quicksilver
- base_2:
  - plugins/jquery.livesearch
  - rails
  - sites/application
- root_layout:
  - jquery.min
  - jquery.ui.core
  - jquery.ui.widget
  - jquery.ui.position
- sites_general_home:
  - plugins/galleria
  - sites/home_sites
- sites_home:
  - sites/home
  - sites/mercatorProjection
  - sites/IOMMarker
  - sites/labels_style
  - sites/overview_map
- clusters_sectors_show:
  - sites/mercatorProjection
  - sites/IOMMarker
  - sites/labels_style
  - sites/overview_map
  - sites/location
- georegion_show:
  - sites/location
  - sites/mercatorProjection
  - sites/IOMMarker
  - sites/labels_style
  - sites/georegion_map
- organizations_show:
  - sites/location
  - sites/mercatorProjection
  - sites/IOMMarker
  - sites/labels_style
  - sites/overview_map
- projects_show:
  - plugins/galleria
  - plugins/galleria.classic
  - sites/project
  - sites/mercatorProjection
  - sites/IOMMarker
  - sites/labels_style
  - sites/overview_map

stylesheets:
- base:
  - sites/jscroll
  - sites/layout
