development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: localhost
  database: iom_development
  username: postgres
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_test
  username: postgres
  password:

staging:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom
  username: postgres
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_production
  username: postgres
  password:
